route:
  group_by: ['alertname']
  receiver: email-notifications

receivers:
- name: 'email-notifications'
  email_configs:
  - to: rrka79wal@gmail.com
    from: rrka79wal@gmail.com
    smarthost: localhost:25
    require_tls: false
    send_resolved: true
