global:
  resolve_timeout: 1m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: EMAIL_ID
  smtp_auth_username: EMAIL_ID
  smtp_auth_password: <pwd>


route:
  receiver: 'email-notifications'

receivers:
- name: email-notification
  email_configs:
  - to: EMAIL_ID
    from: EMAIL_ID
    smarthost: smtp.gmail.com:587
    auth_username: EMAIL_ID
    auth_identity: EMAIL_ID
    auth_password: <pwd>
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
